# Generated by Django 5.2.4 on 2025-08-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='title',
        ),
    ]
