# Generated by Django 6.0.2 on 2026-02-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_remove_journalentry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(choices=[('happy', '😊 Happy'), ('sad', '😢 Sad'), ('angry', '😠 Angry'), ('frustrated', '😤 Frustrated'), ('neutral', '😐 Neutral'), ('excited', '🤩 Excited'), ('anxious', '😰 Anxious'), ('confused', '😵\u200d💫 Confused'), ('calm', '😌 Calm'), ('tired', '🥱 Tired'), ('stressed', '😖 Stressed')], default='neutral', max_length=20),
        ),
    ]
